### PR TITLE
add BusyAgentPercentage metric

### PR DESCRIPTION
**Pull request by arromer**
adding `AgentUsagePercentage` metric, which will be useful in order to implement target tracking autoscaling, see: https://docs.aws.amazon.com/autoscaling/ec2/userguide/as-scaling-target-tracking.html

Also fixed unit tests which were failing with
```
=== RUN   TestCollectorWithNoJobsForAllQueues
2019/03/28 12:10:03 Collecting agent metrics for all queues
--- FAIL: TestCollectorWithNoJobsForAllQueues (0.00s)
    collector_test.go:72: No organization slug was found in the metrics response
```

### CODE REVIEW

**Review by uri-canva — CHANGES_REQUESTED** [review]
How is scaling by tracking usage percentage fundamentally different from tracking idle agents?

**Comment by uri-canva** [comment]
Current https://github.com/buildkite/elastic-ci-stack-for-aws uses https://github.com/buildkite/buildkite-agent-scaler for reference.

**Comment by uri-canva** [comment]
Scaling to number of agents = number of running jobs + number of scheduled jobs: https://github.com/buildkite/buildkite-agent-scaler/blob/8bb509f42e53b07b826650b2a50e2ce6d7ca65e4/scaler/scaler.go#L93.

**Comment by arromer** [comment]
this is basically the same as scaling based on the number of idle agents, unfortunately target tracking is only able to scale out if the metric is higher than the target value

> A target tracking scaling policy assumes that it should scale out your Auto Scaling group when the specified metric is above the target value. You cannot use a target tracking scaling policy to scale out your Auto Scaling group when the specified metric is below the target value

Also target tracking scaling is supposed to do all those calculations for us, that's why I want to test it out.

**Review by uri-canva — APPROVED** [review]
Ok, sounds good then, but call the metric `BusyAgentPercentage` to mirror `BusyAgentCount`.

**Pull request closed without merging**
